
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract magazin {

    uint32 public timestamp;

    string[] public myArr = ["Петя", "Лёша", "Егор"];



    constructor() public {

        require(tvm.pubkey() != 0, 101);

        require(msg.pubkey() == tvm.pubkey(), 102);

        tvm.accept();
        timestamp = now;
    }

    modifier checkOwnerAndAccept {

		require(msg.pubkey() == tvm.pubkey(), 102);
		tvm.accept();
		_;
	}

    function deleteOchered() public checkOwnerAndAccept {
        
        for (uint i = 0; i < myArr.length - 1; i++){
            myArr[i] = myArr[i+1];
        }
        myArr.pop();

    }

    function addOchered(string value) public checkOwnerAndAccept{

        myArr.push(value);
        
    }

}
